#!/usr/bin/env python3

import datetime

import startup


README = 'README.rst'

print('Generate %s from startup.__doc__' % README)
with open(README, 'w') as readme:
    readme.write(startup.__doc__)
    readme.write('\n\n')
    readme.write('.. Generated by %s at %s\n' %
                 (__file__, datetime.datetime.now()))
